#ifndef _AVT_FUNC_ID_H
#define _AVT_FUNC_ID_H
/*
	功能ID宏定义
*/
//
//#define		AVT_FUNC_ID_REALCONNECT				10001				//播放实时
//#define		AVT_FUNC_ID_REALDISCONNECT			10002				//断开实时
//#define		AVT_FUNC_ID_RECORDPLAYSTART			20001				//播放录像
//#define		AVT_FUNC_ID_RECORDPLAYSTOP			20002				//断开录像
//#define		AVT_FUNC_ID_PTZ						30001				//PTZ控制
//#define		AVT_FUNC_ID_RECORDSEARCH			40001				//录像文件查询
//#define		AVT_FUNC_ID_CAPTURE					90001				//抓图
//#define		AVT_FUNC_ID_IMAGE_SET				70001				//图像参数设置
//#define		AVT_FUNC_ID_IMAGE_GET				70002				//图像参数获取
//#define		AVT_FUNC_ID_IMAGE_DEFAULT			70003				//默认图像参数设置
//#define		AVT_FUNC_ID_SOUND_OPEN				70004				//打开音频
//#define		AVT_FUNC_ID_SOUND_CLOSE				70005				//关闭音频
//#define		AVT_FUNC_ID_OSDNAME_SHOW			70006				//显示OSD名称
//#define		AVT_FUNC_ID_OSDNAME_HIDE			70007				//隐藏OSD名称
//#define		AVT_FUNC_ID_OSDTIME_SHOW			70008				//显示OSD时间
//#define		AVT_FUNC_ID_OSDTIME_HIDE			70009				//隐藏OSD时间
//#define		AVT_FUNC_ID_GETSTREAMRATE			70010				//获取当前连接流量
//#define		AVT_FUNC_ID_ADJUSTVIDEOPARAM		70011				//动态切换音视频参数
//#define		AVT_FUNC_ID_LOCALRECORDSTART		70012				//开始本地录像
//#define		AVT_FUNC_ID_LOCALRECORDSTOP			70013				//停止本地录像
//#define		AVT_FUNC_ID_RECORDCONTROL			70014				//录像控制
//#define		AVT_FUNC_ID_DEINTERLACE_OPEN		70015				//打开解码去隔行
//#define		AVT_FUNC_ID_DEINTERLACE_CLOSE		70016				//关闭解码去隔行
//#define		AVT_FUNC_ID_SETYUVCALLBACK			70017				//设置获取YUV视频流回调函数
//#define		AVT_FUNC_ID_RX2TX_CONNECT			70018				//建立TX至RX的音视频连接
//#define		AVT_FUNC_ID_RX2TX_DISCONNECT		70019				//断开TX至RX的音视频连接
//#define		AVT_FUNC_ID_DATA_CONNECT			70020				//建立透明串口通道
//#define		AVT_FUNC_ID_DATA_DISCONNECT			70021				//断开透明串口通道
//#define		AVT_FUNC_ID_UPDATETIME				70022				//同步机箱时间
//#define		AVT_FUNC_ID_SETVIDEOPARAM			70023				//设置视频参数
//#define		AVT_FUNC_ID_SETAUDIOPARAM			70024				//设置音频参数
//#define		AVT_FUNC_ID_SETDATAPARAM			70025				//设置数据参数
//#define		AVT_FUNC_ID_QUERY_CONNECT			70026				//查询机箱已建立的连接
//#define		AVT_FUNC_ID_SET_RMADDR				70027				//设置资源管理器的IP地址
//#define		AVT_FUNC_ID_GET_RMADDR				70028				//获取资源管理器的IP地址
//#define		AVT_FUNC_ID_RESTART					70029				//远程重启
//#define		AVT_FUNC_ID_SET_MACHINE				70030				//修改机箱IP地址和机箱名称
//#define		AVT_FUNC_ID_GET_MACHINE				70031				//获取机箱信息
//#define		AVT_FUNC_ID_GET_NETPARAM			70032				//获取机箱网络参数
//#define		AVT_FUNC_ID_SET_NETPARAM			70033				//设置机箱网络参数
//#define		AVT_FUNC_ID_GET_BOARD				70034				//获取机箱板卡
//#define		AVT_FUNC_ID_GET_VIDEOPARAM			70035				//获取当前视频参数
//#define		AVT_FUNC_ID_GET_AUDIOPARAM			70036				//获取当前音频参数
//#define		AVT_FUNC_ID_GET_DATAPARAM			70037				//获取当前串口参数
//#define		AVT_FUNC_ID_ALARM_OUT				70038				//设置告警输出端口
//#define		AVT_FUNC_ID_ALARM_CALLBACK			70039				//设置上传告警回调函数
//#define		AVT_FUNC_ID_SET_HEARBEAT			70040				//设置心跳参数


enum AVT_FUNCID
{
		AVT_FUNC_ID_REALCONNECT				=10001,				//播放实时
		AVT_FUNC_ID_REALDISCONNECT			=10002,				//断开实时
		AVT_FUNC_ID_REALCONNECT_TS			=10003,				//播放TS流实时
		AVT_FUNC_ID_REALDISCONNECT_TS		=10004,				//断开TS流实时
        AVT_FUNC_ID_STARTTALKBACK			=10005,				//开启对讲
        AVT_FUNC_ID_STOPTALKBACK			=10006,				//停止对讲
        AVT_FUNC_ID_CHECKISSUPPORTTALKBACK	=10007,				//检测客户端是否支持对讲
		AVT_FUNC_ID_RECORDPLAYSTART			=20001,				//播放录像
		AVT_FUNC_ID_RECORDPLAYSTOP			=20002,				//断开录像
		AVT_FUNC_ID_PTZ						=30001,				//PTZ控制
        AVT_FUNC_ID_GETCAMERALIST			=30002,				// 获取摄像机列
		AVT_FUNC_ID_RECORDSEARCH			=40001,				//录像文件查询
		AVT_FUNC_ID_CAPTURE					=90001,				//抓图
		AVT_FUNC_ID_IMAGE_SET				=70001,				//图像参数设置
		AVT_FUNC_ID_IMAGE_GET				=70002,				//图像参数获取
		AVT_FUNC_ID_IMAGE_DEFAULT			=70003,				//默认图像参数设置
		AVT_FUNC_ID_SOUND_OPEN				=70004,				//打开音频
		AVT_FUNC_ID_SOUND_CLOSE				=70005,				//关闭音频
		AVT_FUNC_ID_OSDNAME_SHOW			=70006,				//显示OSD名称
		AVT_FUNC_ID_OSDNAME_HIDE			=70007,				//隐藏OSD名称
		AVT_FUNC_ID_OSDTIME_SHOW			=70008,				//显示OSD时间
		AVT_FUNC_ID_OSDTIME_HIDE			=70009,				//隐藏OSD时间
		AVT_FUNC_ID_GETSTREAMRATE			=70010,				//获取当前连接流量
		AVT_FUNC_ID_ADJUSTVIDEOPARAM		=70011,				//动态切换音视频参数
		AVT_FUNC_ID_LOCALRECORDSTART		=70012,				//开始本地录像
		AVT_FUNC_ID_LOCALRECORDSTOP			=70013,				//停止本地录像
		AVT_FUNC_ID_RECORDCONTROL			=70014,				//录像控制
		AVT_FUNC_ID_DEINTERLACE_OPEN		=70015,				//打开解码去隔行
		AVT_FUNC_ID_DEINTERLACE_CLOSE		=70016,				//关闭解码去隔行
		AVT_FUNC_ID_SETYUVCALLBACK			=70017,				//设置获取YUV视频流回调函数
		AVT_FUNC_ID_RX2TX_CONNECT			=70018,				//建立TX至RX的音视频连接
		AVT_FUNC_ID_RX2TX_DISCONNECT		=70019,				//断开TX至RX的音视频连接
		AVT_FUNC_ID_DATA_CONNECT			=70020,				//建立透明串口通道
		AVT_FUNC_ID_DATA_DISCONNECT			=70021,				//断开透明串口通道
		AVT_FUNC_ID_UPDATETIME				=70022,				//同步机箱时间
		AVT_FUNC_ID_SETVIDEOPARAM			=70023,				//设置视频参数
		AVT_FUNC_ID_SETAUDIOPARAM			=70024,				//设置音频参数
		AVT_FUNC_ID_SETDATAPARAM			=70025,				//设置数据参数
		AVT_FUNC_ID_QUERY_CONNECT			=70026,				//查询机箱已建立的连接
		AVT_FUNC_ID_SET_RMADDR				=70027,				//设置资源管理器的IP地址
		AVT_FUNC_ID_GET_RMADDR				=70028,				//获取资源管理器的IP地址
		AVT_FUNC_ID_RESTART					=70029,				//远程重启
		AVT_FUNC_ID_SET_MACHINE				=70030,				//修改机箱IP地址和机箱名称
		AVT_FUNC_ID_GET_MACHINE				=70031,				//获取机箱信息
		AVT_FUNC_ID_GET_NETPARAM			=70032,				//获取机箱网络参数
		AVT_FUNC_ID_SET_NETPARAM			=70033,				//设置机箱网络参数
		AVT_FUNC_ID_GET_BOARD				=70034,				//获取机箱板卡
		AVT_FUNC_ID_GET_VIDEOPARAM			=70035,				//获取当前视频参数
		AVT_FUNC_ID_GET_AUDIOPARAM			=70036,				//获取当前音频参数
		AVT_FUNC_ID_GET_DATAPARAM			=70037,				//获取当前串口参数
		AVT_FUNC_ID_ALARM_OUT				=70038,				//设置告警输出端口
		AVT_FUNC_ID_ALARM_CALLBACK			=70039,				//设置上传告警回调函数
		AVT_FUNC_ID_SET_HEARBEAT			=70040,				//设置心跳参数
		AVT_FUNC_ID_GETENCODERSTATE			=70041,				//获取编码器状态
		AVT_FUNC_ID_GETDECODERSTATE			=70042,				//获取解码器状态
		AVT_FUNC_ID_SETALARM				=70043,				//设置报警接收
		AVT_FUNC_ID_SETOSDEX				=70044,				//设置扩展OSD
		AVT_FUNC_ID_SHOWENCODEROSD			=70045,				//显示编码器OSD
		AVT_FUNC_ID_SETENCODEROSD			=70046,				//设置编码器OSD
		AVT_FUNC_ID_DRAWSELF				=70047,				//画框
		AVT_FUNC_ID_RECORDFILEPLAYSTART		=70048,				//播放本地录像文件
		AVT_FUNC_ID_RECORDFILEPLAYSTOP		=70049,				//停止播放本地录像文件
		AVT_FUNC_ID_SAVETOCVSS              =70050,             //保存DVSS上的实时视频到CVSS中
		AVT_FUNC_ID_STOPSAVETOCVSS          =70051,             //停止存储到CVSS上
		AVT_FUNC_ID_SETOSDPARAM             =70052,             //设置OSD参数信息
		AVT_FUNC_ID_IFLOCALRECORDING        =70053,             //判断是否正处于本地录像状态
		AVT_FUNC_ID_EXCUTECOMMAND120        =70054,				//执行EVSD 120指令
		AVT_FUNC_ID_RECORDPLAYTORX			=70055,				//硬解回放
		AVT_FUNC_ID_AUD330SCALE				=70056,				//Aud330缩放
		AVT_FUNC_ID_RECORDDOWNLOAD			=70057,				//录像下载
		AVT_FUNC_ID_RECORDDOWNLOADSTOP		=70058,				//停止录像下载
		AVT_FUNC_ID_STARTRECORDTOCVSS		=70059,				//开始录像到CVSS
		AVT_FUNC_ID_STOPRECORDTOCVSS		=70060,				//停止录像到CVSS
		AVT_FUNC_ID_EXCUTECOMMAND538		=70061,				//执行538指令
		AVT_FUNC_ID_QUERYCAMERAINFO			=70062,				//查询华三所有摄像机的信息
		AVT_FUNC_ID_SETRXOSDPARAM			=70063,				//设置解码器的OSD信息
		AVT_FUNC_ID_RECORDCONTROL2RX		=70064,				//硬解录像控制
		AVT_FUNC_ID_SETRXOSDDRAWEX			=70065,				//设置RX的OSD DRAW扩展信息
		AVT_FUNC_ID_SETRXOSDNAMEEX			=70066,				//设置RX的OSD NAME扩展信息
		AVT_FUNC_ID_VASSTARTDISPLAY			=70067,				//向VAS发送“启动显示”指令
		AVT_FUNC_ID_VASSTOPDISPLAY			=70068,				//向VAS发送“停止显示”指令
		AVT_FUNC_ID_CVSSGETSPACEINFO		=70069,				//获取CVSS的磁盘空间信息

		AVT_FUNC_ID_STARTREALCALLBACK		=70070,				//开始实时原始流回调，成功会返回一个句柄，失败返回的句柄为0
		AVT_FUNC_ID_STOPREALCALLBACK		=70071,				//结束实时原始流回调
		AVT_FUNC_ID_STARTRECORDCALLBACK		=70072,				//开始录像原始流回调，成功会返回一个句柄，失败返回的句柄为0
		AVT_FUNC_ID_STOPRECORDCALLBACK		=70073,				//结束录像原始流回调
		AVT_FUNC_ID_STARTDOWNLOADCALLBACK	=70074,				//开始录像下载的原始流回调，成功会返回一个句柄，失败返回的句柄为0
		AVT_FUNC_ID_STOPDOWNLOADCALLBACK	=70075,				//结束录像下载的原始流回调
		AVT_FUNC_ID_RECORDCONTROLEX			=70076,				//适用于录像原始流回调时的录像控制

		AVT_FUNC_ID_AUD330SETWINDOWMODE		=70077,				//设置AUD330的分屏模式
		AVT_FUNC_ID_AUD330GETWINDOWSSTATE	=70078,				//获取AUD330的所有窗口状态
		AVT_FUNC_ID_AUD330UPDATECONFIG		=70079,				//AUD330更新配置文件
		AVT_FUNC_ID_SETPEOPLEFLOWDRAW		=70080,				//设置是否显示人群密度到窗口上。
		AVT_FUNC_ID_QUERY_GATEWAYINFO		=70081,				//查询网管信息（告警信息）
		AVT_FUNC_ID_QUERY_RECORD_CALLBACK   =70082,				//以回调方式查询CVSS上的录像信息
		AVT_FUNC_ID_GET_PLAYING_TIME		=70083,				//获取当前播放的时间点
		AVT_FUNC_ID_SET_AUD330_EXTEND_OSD   =70084,				//设置AUD330的扩展OSD信息
		AVT_FUNC_ID_SET_AUD330_VIDEO_RATIO  =70085,				//设置AUD330的视频显示模式（16：9，4：3，全屏等）
		AVT_FUNC_ID_QUERY_VIDEOLOSTINFO		=70086,				//查询编码器，wvsms，以及cvss上所有摄像机当前视频状态（视频丢失，视频恢复）
		AVT_FUNC_ID_UPLOAD_CAMERAINFO		=70087,				//上传摄像机配置信息到编码器上
		AVT_FUNC_ID_DOWNLOAD_CAMERAINFO		=70088,				//从编码器上下载摄像机配置信息
		AVT_FUNC_ID_SETOSDTRANSPARENT		=70089,				//设置OSD背景透明度（软解）
		AVT_FUNC_ID_SETRXOSDTRANSPARENT		=70090,				//设置解码器的OSD背景透明度
		AVT_FUNC_ID_QUERYGBWVSMSCONNECT		=70091,				//以国标方式获取WVSMS已经建立的连接。
		AVT_FUNC_ID_MDPCCONFIG				=70092,				//设置MDPC端口占用满之后的处理方式
		AVT_FUNC_ID_GET_MDPCCONFIG			=70093,				//获取MDPC工作模式
		AVT_FUNC_ID_SET_DIGITALZOOM			=70094,				//设置放大区域
		AVT_FUNC_ID_RESET_DIGITALZOOM		=70095,				//重置放大区域
		AVT_FUNC_ID_Move_DIGITALZOOM		=70096,				//移动放大区域
		AVT_FUNC_ID_GET_BUFFERFRAMES		=70097,				//获得缓冲帧数
		AVT_FUNC_ID_SET_BUFFERFRAMES		=70098,				//设置缓冲帧数
		AVT_FUNC_ID_GET_VIDEORESOLUTION		=70099,				//获取视频分辨率
		AVT_FUNC_ID_DOWNLOAD_RECORD_WITH_PROGRESS = 70100,		//录像下载（带进度回调）
		AVT_FUNC_ID_REWINDRECORDSTART		=70101,				//开始录像回放到看
		AVT_FUNC_ID_REWINDRECORDSTOP		=70102,				//停止录像回放到看
		AVT_FUNC_ID_REWINDRECORDPLAYMODE	=70103,				//设置录像回放到看播放方式
		AVT_FUNC_ID_QUERY_FRAMECOUNT_PERMINUTE = 70104,			//查询CVSS指令时间内每分钟的录像的帧数
		AVT_FUNC_ID_SET_DIGITALZOOMYUV		=70105,				//设置放大区域，针对YUV
		AVT_FUNC_ID_GET_VASPMT				=70106,				//获取VAS的端口映射表
		AVT_FUNC_ID_SET_VASPMT				=70107,				//设置VAS的端口映射表
		AVT_FUNC_ID_ISDRAWVASCIRCLE			=70108,				//设置是否显示VAS的框
		AVT_FUNC_ID_SET_VASOSDINFO			=70109,				//设置VAS报警OSD
		AVT_FUNC_ID_GET_VASANALYSISSTATUS	=70110,				//查询VAS的分析状态
		AVT_FUNC_ID_GET_VASALARMINFO		=70111,				//查询VAS的报警信息
		AVT_FUNC_ID_SET_CVSSBACKUPPLAN		=70112,				//设置CVSS的备份计划
		AVT_FUNC_ID_QUERY_RECORDFILE_SIZE	=70113,				//查询CVSS指定时间内指定摄像机的录像文件大小
		AVT_FUNC_ID_CVSS_STOP_STORAGEPLAN	=70114,				//停止CVSS的存储计划
		AVT_FUNC_ID_CVSS_RECOVER_STORAGEPLAN	=70115,			//恢复CVSS的存储计划
		AVT_FUNC_ID_CVSS_GET_DELAYSTARTUPTIME	=70116,			//查询CVSS的延时启动时间
		AVT_FUNC_ID_CVSS_SET_DELAYSTARTUPTIME	=70117,			//设置CVSS的延时启动时间
		AVT_FUNC_ID_VAS_GET_PDT				=70118,				//查询VAS预存储时间和录像延时时间
		AVT_FUNC_ID_VAS_SET_PDT				=70119,				//设置VAS预存储时间和录像延时时间
		AVT_FUNC_ID_SYNCHRONIZE_AUD330_OSD	=70120,				//同步Aud330 OSD信息
		AVT_FUNC_ID_SWITCH_AUDIOCARD		=70121,				//切换声卡
		AVT_FUNC_ID_ADJUST_YUV_COLOR		=70122,				//设置亮度，色度，对比度，饱和度
		AVT_FUNC_ID_RESET_YUV_COLOR			=70123,				//重置为默认值，亮度，色度，对比度，饱和度
		AVT_FUNC_ID_GET_YUV_COLOR			=70124,				//获取，亮度，色度，对比度，饱和度
		AVT_FUNC_ID_SET_DECODE_MODE			=70125,				//设置解码库
		AVT_FUNC_ID_SET_AUDIO_CARD			=70126,				//设置声卡输出
		AVT_FUNC_ID_SET_GLOBAL_TSOSDTIME_ENABLE = 70127,		//封装为TS流时，是否增加OSD时间到流中
		AVT_FUNC_ID_SET_VIDEORESOLUTIONCALLBACK = 70128,		//设置视频分辨率回调
		AVT_FUNC_ID_SET_CVSSSTORAGEPLAN		=70129,		        //同步CVSS存储计划
		AVT_FUNC_ID_GET_DECODE_MODE			=70130,				//获取解码库
		AVT_FUNC_ID_GET_MULTICAST_IP		=70131,				//获取组播地址
		AVT_FUNC_ID_SETOSDTIMEEX			=70132,				//设置SDK内部叠加OSD时间
		AVT_FUNC_ID_SETPTZUSERNAME			=70133,				//设置云台占用信息
		AVT_FUNC_ID_DEVICE_UPDATE			=70134,				//给设备升级
		AVT_FUNC_ID_LOG_DOWNLOAD			=70135,				//下载设备日志
		AVT_FUNC_ID_VAS_PARAM_SET		    =70136,		    	//设置视频分析参数
		AVT_FUNC_ID_VAS_PARAM_GET			=70137,				//获取视频分析参数	
		AVT_FUNC_ID_GET_HEARTBEAT            =70138,			//获取心跳参数
		AVT_FUNC_ID_SET_CVSS_REDUCE_MAP     =70139,				//设置CVSS减帧计划映射
		AVT_FUNC_ID_SET_CVSS_REDUCE         =70140,				//CVSS减帧计划
		AVT_FUNC_ID_START_DEHAZE			=70141,				//开启雾透功能
		AVT_FUNC_ID_STOP_DEHAZE				=70142,				//停止雾透功能
		AVT_FUNC_ID_SET_DEHAZE_PARAM		=70143,				//设置雾透参数
		AVT_FUNC_ID_SET_KBC_COMINFO			=70144,				//KBC数据端口的配置
		AVT_FUNC_ID_SET_KBC_CAMERAINFO		=70145,				//KBC摄像机配置
		AVT_FUNC_ID_SET_KBC_CAMERAPRIOR		=70146,				//KBC摄像机优先级配置
		AVT_FUNC_ID_SET_KBC_MONITORINFO		=70147,				//KBC监视器配置
		AVT_FUNC_ID_SET_KBC_MONITORPRIOR	=70148,				//KBC监视器优先级配置
		AVT_FUNC_ID_SET_KBC_USERINFO		=70149,				//KBC设置用户信息
		AVT_FUNC_ID_SET_KBC_TRANSMITWAY		=70150,				//KBC设置传输方式
        AVT_FUNC_ID_GET_REGION_PARAM		=70151,				//获取移动侦测参数
        AVT_FUNC_ID_SET_RETION_PARAM		=70152,				//设置移动侦测参数
        AVT_FUNC_ID_CAPTURE_REMOTE			=70200,				//远程抓图
		AVT_FUNC_ID_VAS_SET_ENABLE			=70211,				//VAS分析算法启停设置
		AVT_FUNC_ID_VAS_GET_ENABLE			=70212,				//获取视频分析启停状态
		AVT_FUNC_ID_GETISDRAWVASCIRCLE		=70213,				//获取是否显示VAS的框
                AVT_FUNC_ID_PTZ_USING				=   70214,          //查询云台占用信息
                AVT_FUNC_ID_VAS_CANCEL_STATIC_OBJECT	=	70215,//取消静态遗留物报警
                AVT_FUNC_ID_LOGIN					=71000,				//登录NICE/NKF平台

		AVT_FUNC_ID_GETCAMANDSITELISTEX		=80000,
		AVT_FUNC_ID_REALCONNECTEX			=80001,				//大华解码库实时播放，可取YUV回调
		AVT_FUNC_ID_RECORDPLAYSTARTEX		=80002,				//大华解码库录像回放，可取YUV回调
		AVT_FUNC_ID_GET_CAMERA_CONFIG		=80003,				//海康获取摄像机分辨率		
		AVT_FUNC_ID_SET_ALARM_CALLBACK		=80004,				//海康设置报警回调
		AVT_FUNC_ID_GET_CAMERA_CONFIG_EX	=80005,				//海康获取摄像机配置
		AVT_FUNC_ID_GET_CAMERA_GETSTREAMNAME = 80006,			//Onvif获取流名称
		AVT_FUNC_ID_GET_RECORDDOWNLOADPOS    =80007,                    //获取录像下载进度
		AVT_FUNC_ID_GET_NVRCHANNUM          =80008,               //获取NVR通道数
		AVT_FUNC_ID_GET_NVRCHANINUSE        =80009,               //获取NVR上在使用的通道
		AVT_FUNC_ID_MATRIX_START_DYNAMIC	=80030,				//海康解码器开启主动解码
		AVT_FUNC_ID_MATRIX_STOP_DYNAMIC		=80031,				//海康解码器停止主动解码
		AVT_FUNC_ID_CDMPIS_GET_DEVICEINFO	=81000,				//传入设备信息(成都地铁车载视频接入)
		AVT_FUNC_ID_GTEDOWNLOAD_PROCESS     =81011,             //IMOS下载录像进度
		AVT_FUNC_ID_GETPRESETS             =81012,            //获取云台预置位

		AVT_FUNC_ID_START_REALPLAY_ES_STREAM	=81500,				//开始实时ES流
		AVT_FUNC_ID_STOP_REALPLAY_ES_STREAM		=81501,				//断开实时ES流
		AVT_FUNC_ID_START_RECORDPLAY_ES_STREAM	=81502,				//开始回放ES流
        AVT_FUNC_ID_STOP_RECORDPLAY_ES_STREAM	=81503,				//断开回放ES流


        GB_FUNC_ID_LOGIN= 70040,//注册
        GB_FUNC_ID_LOGOUT= 70041,//注销

        AVT_FUNC_ID_GET_DEVICE_LIST_ASYNC =82001,	//异步获取设备列表
        AVT_FUNC_ID_GET_DEVICE_LIST_SYNC =82002,		//同步获取设备列表
        AVT_FUNC_ID_SET_VIDEO_PROTOCOL =82003, 		//设置视频流协议
};

#endif//#ifndef _AVT_FUNC_ID_H
