/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MobileAlarmAPI_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace MOBILE_ALARM_API {

} // namespace
