/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MobileAlarmAPI_CONSTANTS_H
#define MobileAlarmAPI_CONSTANTS_H

#include "MobileAlarmAPI_types.h"

namespace MOBILE_ALARM_API {

class MobileAlarmAPIConstants {
 public:
  MobileAlarmAPIConstants();

};

extern const MobileAlarmAPIConstants g_MobileAlarmAPI_constants;

} // namespace

#endif
