// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MobileAlarm.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::MOBILE_ALARM_API;

class MobileAlarmHandler : virtual public MobileAlarmIf {
 public:
  MobileAlarmHandler() {
    // Your initialization goes here
  }

  void AlarmTrigger(std::string& _return, const std::string& content) {
    // Your implementation goes here
    printf("AlarmTrigger\n");
  }

  void AlarmQueryList(std::string& _return, const std::string& content) {
    // Your implementation goes here
    printf("AlarmQueryList\n");
  }

  void AlarmQueryDetail(std::string& _return, const std::string& content) {
    // Your implementation goes here
    printf("AlarmQueryDetail\n");
  }

  void AlarmReset(std::string& _return, const std::string& content) {
    // Your implementation goes here
    printf("AlarmReset\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MobileAlarmHandler> handler(new MobileAlarmHandler());
  shared_ptr<TProcessor> processor(new MobileAlarmProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

