/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MobileAlarmAPI_constants.h"

namespace MOBILE_ALARM_API {

const MobileAlarmAPIConstants g_MobileAlarmAPI_constants;

MobileAlarmAPIConstants::MobileAlarmAPIConstants() {
}

} // namespace

